# Generated by Django 4.1.2 on 2022-12-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_hotel_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.RenameModel(old_name="Hotel", new_name="Image",),
    ]
