# Generated by Django 4.1.2 on 2022-12-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_hotel_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="age",),
        migrations.RemoveField(model_name="user", name="classes",),
        migrations.RemoveField(model_name="user", name="imagepath",),
        migrations.RemoveField(model_name="user", name="semester",),
        migrations.AddField(
            model_name="user",
            name="haveModel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nim",
            field=models.CharField(default="password", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
