# Generated by Django 4.1.2 on 2022-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_user_age_remove_user_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nim",
            field=models.CharField(default="password", max_length=100, unique=True),
        ),
    ]
