# Generated by Django 4.1.2 on 2022-12-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_nim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nim",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
