# Generated by Django 4.1.2 on 2022-12-16 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_nim"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAbsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="tempimages/")),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="userId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="models/"),
        ),
    ]
