# Generated by Django 4.1.2 on 2022-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_course_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
