# Generated by Django 4.1.2 on 2022-11-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=50, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.image')),
            ],
        ),
    ]
