# Generated by Django 4.1.2 on 2022-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=50, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('imagepath', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
